title: Neues Zeug

tabs:
  tab_compositions: tabs/compositions

  tab_participants: tabs/participants

  tab_partners: tabs/partners

  tab_settings: tabs/settings

  tab_analytics:
    label: Statistik
    icon: chart
    columns:
      column_matomo_main:
        width: 3/4
        sections:
          main:
            type: matomo-main
      column_matomo_sidebar:
        width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
